### ISSUE TITLE
How to set the 'goBackURL' parameter in a Angular 7 app?

### ISSUE THREAD

**Issue by Avrohom** [AnthonyNahas/ngx-auth-firebaseui#156]
### Bug Report or Feature Request (mark with an `x`)

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] Help needed
```

### OS and Version?
 Windows 10. 

### Versions
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.1.3
Node: 8.11.1
OS: win32 ia32
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cdk                      7.1.1
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.1.1
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Repro steps
```
<ngx-auth-firebaseui *ngIf="thisUser==null"
                     [guestEnabled]="false"
                     [goBackURL]="counter"
                     (onSuccess)="printUser($event)"
                     (onError)="printError($event)">
</ngx-auth-firebaseui>
<ngx-auth-firebaseui-user *ngIf="thisUser"></ngx-auth-firebaseui-user>
```

### Desired functionality

I would like to see that after a login the user gets redirected to a certain page or route.

### Mention any other details that might be useful

It doesn't seem that `goBackURL` has any affect at all on redirecting. Also, when signing out from inside the `ngx-auth-firebaseui-user` component the console shows the following error: 
> GET https://localhost:44367/null 404                                                                                       null:1

So I assume that somehow we need to specify a redirect URL for after signing out. I couldn't find in the documentation anything related to this on how and where to define such.

Also, I was wondering if I can have provider login inside one of my windows / Component and not in an external window?

Last, where can I change the toast message greeting from 'hallo' to 'hello'?

**Comment by beeman** [comment]
From looking at your example `[goBackURL]="counter"` this will try and look up the property `counter` in the component class. If it won't find it, it will return null...

If you want to redirect to the route with the name `counter` make it should work like this: `goBackUrl="counter"`, without the square brackets.

Another option is to define a class property with a route:

```typescript
export class SomeComponent {
	public counter = '/my-redirect-path'
}
```

**Comment by Avrohom** [comment]
Hi @beeman 

Thanks for your input.
![image](https://user-images.githubusercontent.com/6719297/50047097-041c1b00-00a7-11e9-9f0d-2bfbd0e4036c.png)

I think that the documentation on goBackURL is misleading. From inspecting the code it seems to me that this option is the redirect property **for AFTER Clicking the verify link inside the verify email**. It has nothing to do with successful or unsuccessful authentication redirection, and most definitely after sign out.

The console error after sign out - seems to me - to have nothing to do with ngx-auth-firebaseui. It is the way it is implemented by Firebase themselves. See the following link.
[https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signOut](url)

ngx-auth-firebaseui calls this method basically.

**Comment by AnthonyNahas** [comment]
@Avrohom first of all thanks for opening this thread to clarify few things regarding this package and the module's documentation.

I am gonna split your above questions in several steps:

## 1

> It doesn't seem that goBackURL has any affect at all on redirecting. Also, when signing out from inside the ngx-auth-firebaseui-user component the console shows the following error:


The `goBackURL` input is actually only responsible to redirect the new created users to a specific route when requested through the button `Go back to the sign up page` see the illustration of this scene [here](https://raw.githubusercontent.com/AnthonyNahas/ngx-auth-firebaseui/master/assets/v1.0.0/png/registered_confirm.png). It has nothing to do with redirection after signing in/out ... 
An example for this input is under development now within the demo app.
Do you have any suggestion to rename the `goBackURL` input to something more intuitive ... ? 
However  I admit that the documentation of this property is 100% misleading! 
I will change it to the following: `goBackURL` the url to redirect to after creating a new user and clicking the `go back` button 

Furthermore, you suggested indirectly above a new feature which is to automatically redirect users to a specific route on signing in/out... Would be that helpful for the developers? Or should we keep that logic outside the `ngx-auth-firebaseui`... ? If yes, I would like to ask you if you can open a new appropriate issue as a feature for that ❤️ 

## 2

> Also, I was wondering if I can have provider login inside one of my windows / Component and not in an external window?

I didn't understand the question.. I am sorry.. could you be more specific or provide an example ?? ...


## 3

> Last, where can I change the toast message greeting from 'hallo' to 'hello'?

Please see the demo app [here](https://ngx-auth-firebaseui.firebaseapp.com/examples/messages) | [documentation](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/README.MD#ngx-auth-firebaseuingx-auth-firebaseui-1)

please use `messageOnAuthSuccess` and `messageOnAuthError` to customize the toast messages  

However, since this package uses the english language as default I will replace `hallo` with `hello`

**Comment by Avrohom** [comment]
Hi @AnthonyNahas. 
With regards to  
### 1
I think that goBackURL is OK as long the description in the documentation is clear enough.
As to what to implement an redirect on sign in / out. I would rather leave it for the developer as things can get very messy hear. Anyone who will want to implement this, needs just to subscribe to `user` or `authState` and react accordingly.

### 2 
I was wondering if when signing in with a provider such as Google, Facebook etc. If we can have it done within the app's own window. So no popup (external) window.

### 3
I know how to use `messageOnAuthSuccess`. But question is how to interpolate it with `user.displayName`. I have tried a lot. Although I know that the `ngOnChanges()` is applied to this `@Input` parameter. Problem is: I get the newly signed-in user **after** the toast message. Such a shame. Otherwise we could provide our own customized message with user name interpolation within.

**Comment by AnthonyNahas** [comment]
@Avrohom --> 

1. 🆗 
2. I will open an appropriate issue as a feature to support [signin with pop or redirection](https://firebase.google.com/docs/auth/web/google-signin) 👍 
3. You have right! I will refactor and improve the code to make that working ;) 

So I will close now this issue and open two another 📟

**Comment by Avrohom** [comment]
Thanks ever so much @AnthonyNahas for the update.

Happy to be of some kind of a help.

**Comment by cupidchan** [comment]
I am not to this authentication package and have the same issue brought up by @Avrohom - not sure how can I redirect to my main app with a valid user information after successfully login. I saw that we can "subscribe to user or authState", is there any code sample that I can check? @AnthonyNahas, this will be a great example to show the end-to-end authentication flow of how to use ngx-auth-firebaseui, can you please point me the direction if you have already got some examples? Thanks a lot!
