### ISSUE TITLE
assets not loaded

### ISSUE THREAD

**Issue by FVerhamme** [AnthonyNahas/ngx-auth-firebaseui#161]
If you serve your app with "ng serve --base-href /subfolder/" then you get errors that the assets "google.svg" and "facebook.svg" could not load from "http://localhost:4200/assets/google.svg" or "http://localhost:4200/assets/mdi/facebook.svg"

What needs to be changed to respect the base-href?
The assets should be loaded from http://localhost:4200/subfolder/assets/google.svg or http://localhost:4200/subfolder/assets/mdi/facebook.svg

**Comment by AnthonyNahas** [comment]
Hi @FVerhamme, the is rather a configuration issue... Can u please tell me what is the value of base href in 

> index.html

 file ?

**Comment by FVerhamme** [comment]
Inside the index.html its the following
<base href="/subfolder/">

**Comment by AnthonyNahas** [comment]
@FVerhamme did you solve that problem ?
Please make sure by deploying your app you should use the deploy url arg for the angular cli - [see here for more info](https://angular.io/guide/deployment)

since this issue is not related to the package, I will close this issue  now.
If you need help or having trouble with your angular app -> please feel free to contact us on gitter [here](https://gitter.im/ngx-auth-firebaseui/Lobby)
