### ISSUE TITLE
Disable the Register Tab

### ISSUE THREAD

**Issue by Francois-Belanger** [AnthonyNahas/ngx-auth-firebaseui#202]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### OS and Version?
 Mojave

### Versions
Angular CLI: 7.2.3
Node: 10.15.0

### Desired functionality
 Have the option to remove the Register Tab

**Comment by AnthonyNahas** [comment]
@belf2601 thanks for requesting this feature (related to #174 )

Do you have any suggestion how to make the UI better to suit your app ?

I am looking forward to support multiple themes in the future

**Comment by belf2601** [comment]
Hi, I really just don't need user to register accounts.  It's for a corporate company and accounts are created by the admin.

But I love the design and the reset password etc :-)

Thanks

**Comment by AnthonyNahas** [comment]
ahh I see! Thanks for the kind of sweet words ❤️ 

take a look the api [here](https://github.com/AnthonyNahas/ngx-auth-firebaseui#api)

there is a component input called `guestEnabled` to allow the developer to control the `guest` authentication feature. What do u think if I implement a similar process for the `signin` and `register` features so that the developer can choose the right features and options to suit their apps ?

**Comment by belf2601** [comment]
Yes I think it would be great :-). Something like:
registerEnabled Input() | boolean | true | whether the user can create a new account

Thanks

**Comment by AnthonyNahas** [comment]
I will implement that in the near future 👌

**Comment by AnthonyNahas** [comment]
your request has been implemented! 
I've enhanced the library so that the developer can disable the `reset password` too!
Just think about it! In your case -> you need to disable the registration.. so it make sense to disable the `forgot password button` too in order to prevent that action! Only admins should be able to create/update/reset the user's account.

Result -> 2 new input 
- `registrationEnabled = true;`
<img width="523" alt="bildschirmfoto 2019-02-28 um 22 32 24" src="https://user-images.githubusercontent.com/20149774/53600918-1c320f80-3bab-11e9-8258-53ac6b0053cd.png">
- `resetPasswordEnabled = true;`
<img width="540" alt="bildschirmfoto 2019-02-28 um 22 32 12" src="https://user-images.githubusercontent.com/20149774/53600922-205e2d00-3bab-11e9-855d-91d9aad11a27.png">


[ngx-auth-firebaseui v2.4.0 is now live](https://www.npmjs.com/package/ngx-auth-firebaseui)

thanks for contributing and cheers 🍻

**Comment by Francois-Belanger** [comment]
I confirm, it works great !

Thanks
