### ISSUE TITLE
Missing or Insufficient permissions in ngx-auth-firebaseui when try to register

### ISSUE THREAD

**Issue by chakram341** [AnthonyNahas/ngx-auth-firebaseui#218]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by AnthonyNahas** [comment]
Can you please provide more info about the related issue? Please consider to fill the issue template to validate your issue. Thank you

**Comment by FlashTime** [comment]
i have same error

Missing or insufficient permissions.

ngx-auth-firebaseui.es5.js:568 FirebaseError: Missing or insufficient permissions.
    at new FirestoreError (http://localhost:4200/vendor.js:151848:28)
    at http://localhost:4200/vendor.js:158790:46
    at Y.<anonymous> (http://localhost:4200/vendor.js:158735:21)
    at nb (http://localhost:4200/vendor.js:179327:195)
    at Y.g.dispatchEvent (http://localhost:4200/vendor.js:179325:304)
    at Z.ua (http://localhost:4200/vendor.js:179378:35)
    at Ad.g.Ga (http://localhost:4200/vendor.js:179369:203)
    at ic (http://localhost:4200/vendor.js:179333:371)
    at kc (http://localhost:4200/vendor.js:179331:354)
    at M.g.Ka (http://localhost:4200/vendor.js:179330:437)


![image](https://user-images.githubusercontent.com/11992161/57148100-31a10100-6dc9-11e9-948a-2e8c6d698143.png)

html tempalte 

<ngx-auth-firebaseui
        [privacyPolicyUrl]="'...'"
        [tosUrl]="'...'"
        [providers]="[]"
        [guestEnabled]="false"
        (onSuccess)="printUser($event)"
        (onError)="printError($event)"
      ></ngx-auth-firebaseui>



.ts file 

  printUser(event) {
    // console.log(event);
    console.log("printUser");
  }

  printError(event) {
    // console.error(event);
    console.log("printError");
  }

**Comment by AnthonyNahas** [comment]
pls check this stackoverflow question... 

https://stackoverflow.com/questions/46635830/missing-or-insufficient-permissions-when-writing-to-firestore-using-field-in-acc


are you using your own firebase project key or the one provided in the demo app ??

However, it seems that the firestore rule are wrong configured in your project and the library has nothing to do with the issue...

**Comment by FlashTime** [comment]
you are right

I should put a value to 'allow reading, writing' to true while developing.

I figured it out. I needed to put allow read, write: if true instead of allow read, write: if false in my security rules. Thanks.

![image](https://user-images.githubusercontent.com/11992161/57361792-8653cb80-717d-11e9-8cda-be2f99cd61ef.png)

**Comment by SaidMavlyan** [comment]
ngx-auth-firebaseui has a config field `enableFirestoreSync` which is set true by default.
Setting that field to false in configs, removed mentioned error in my project. 

P.S.
Firebase Authentication works perfectly well without storing user data in Firestore. Because I was seeing Firestore's user collection was filled with user data, I assumed wrongly that Firebase Authentication works that way, which is not the case, all was happening because of the mentioned config option.
