### ISSUE TITLE
Password Recovery Tab - resetPasswordInputText placeholder issue.

### ISSUE THREAD

**Issue by santoshmondal** [AnthonyNahas/ngx-auth-firebaseui#295]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Sierra

### Versions

Angular CLI: 8.0.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.1

### Repro steps

I want to change the placeholder for reset password field, with following 
```
[resetPasswordInputText]="'Password Recovery Email Field'"
```
the placeholder text does not change.

**Comment by AnthonyNahas** [comment]
this is already implemented. Please use the following input

`resetPasswordTabText`

thank you 🍻

**Comment by digitalhurricane-io** [comment]
First of all, awesome project.

Second of all, this is not invalid.

The text specified for 'resetPasswordTabText' also appears in the input box.

**Comment by vbourdeix** [comment]
Indeed, and it seems this issue is the same as https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/295

@AnthonyNahas you need to use a different variable than resetPasswordTabText here https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/561cc51ed971bd369ea78eb94fb4aedfd5a1997a/src/module/components/ngx-auth-firebaseui/auth.component.html#L266

Reset resetPasswordTabText  is the name of the tab and might be something as "Reset password" whereas the mat-label on this line is about the email for which you want to reset the password, which should be something like "Email address of the account".

Currently, the field name is "New password" even if this is a field for an email.

**Comment by AnthonyNahas** [comment]
I would appreciate a PR

**Comment by vbourdeix** [comment]
Ok, I'll try to do it in the coming days.

**Comment by vbourdeix** [comment]
I did not have time to work on it before but here it is : https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/378
