### ISSUE TITLE
Support for Ionic/Capacitor

### ISSUE THREAD

**Issue by mcroker** [AnthonyNahas/ngx-auth-firebaseui#590]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```
I've been having a play at getting ngx-auth-firebaseui working with Capacitor. I wasn't sure if I should just comment on Issue #63 - but decided that Capacitor was distinct from Ionic/Cordova, so I would open a new ticket. Feel free to close this one if you'd prefer to manage there.

Ionic/Capactor presents some challenges common to Ionic/Cordova, e.g. as that it would be nice to be able to use components with the ionic look/feel; but (unless I am missing something) the greater challenge is that firebase doesn't accept 'capacitor' as a valid location.protocol and throws this error `auth/operation-not-supported-in-this-environment: This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled`.

NB: This issue is not specific to this package, and also affects [firebaseui-web](https://github.com/firebase/firebaseui-web/issues/625)

I believe the right approach is to use Capacitor plugin(s) to perform the Social provider authentication on the native layer, and where necessary to pass the retrieved credentials to AngularFireAuth.signInWithCredential().  I have a bare-bones POC of this implemented here, to prove the process worked (sorry, not particularly clean and also has some dead-code...)
https://github.com/mcroker/ngx-auth-firebaseui/blob/feat/ionic/projects/ngx-auth-firebaseui/src/lib/services/auth-process.service.ts

The above POV uses the Capacitor plugins to perform the auth as described above...

- https://github.com/baumblatt/capacitor-firebase-auth
- https://github.com/twogate/cordova-plugin-sign-in-with-apple.  [as the 1st plugin doesn't yet support apple]

I'm raising this issue in the hope that you can validate this approach, and also to discuss if there is any value to fold capacitor/ionic support back in; and what the best way to do that might be....

**Comment by AnthonyNahas** [comment]
since ngx-auth-firebaseui relies on angular material --> if you use ionic you need to install as well angular material

to make it work with ionic could be really challenging.  That's why the perfect idea is to create a standalone library only for ionic without using angular material. Till now I didnt find the right time to start with implementing this library. I know too many developers are waiting for that. I am maintiaing over 15 OS projects, dedicating 4 companies and many other stuff.... so I need some time.

Info: for ionic --> we may need to use firebase plugins rather than web tools

I would love to have someone on board to do that


I will close this ticket right now and continue tracking that with #63 


thank you again
