### ISSUE TITLE
Support for Cordova / Ionic?

### ISSUE THREAD

**Issue by gbarrionuevo** [AnthonyNahas/ngx-auth-firebaseui#63]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Desired functionality

As title says, it's going to support cordova / ionic soon?

**Comment by AnthonyNahas** [comment]
cordova / ionic will be soon supported! However, I don't know whether if I should enhance this project or create a new one like `ionic-auth-firebaseui` ...

what do you think?

would you prefer to use exactly the same UI with material design in ionic ? or to the ionic UI components ?

**Comment by gbarrionuevo** [comment]
Glad to hear It, It would be more clearly to have an ionic-auth... Also id rather material but ir just my perspective, do you have an eta ? Is there a way to contribute or smth?

**Comment by tariqsherriff** [comment]
Awesome code and documentation. Have you added cordova yet?

**Comment by AnthonyNahas** [comment]
thanks @tariqsherriff 

Few weeks ago I created a new [repo](https://github.com/firebaseui/ionic-authentication) for cordova and ionic but I am still busy other stuffs :( 

Would you prefer a seperate project for that to use the ionic components instead of material2 ?

**Comment by tariqsherriff** [comment]
@AnthonyNahas 

yes it'd be great if you could make a separate project using ionic components 💯!  i wish i could help but i am a beginner :(

**Comment by Erim32** [comment]
@AnthonyNahas : do you have any update about this issue ?

**Comment by AnthonyNahas** [comment]
Ionic version of this library is on my roadmap (like the [boostrap version](https://github.com/firebaseui/ng-bootstrap) which is already released).
 However, I am facing too many issues with ionic v4! Here is the active repo of the [ionic-auth-firebaseui](https://github.com/AnthonyNahas/ionic-auth-firebaseui) (last commit few hours ago ;) )

I would maybe support first ionic **v2-3** and later on **v4**

**Comment by Apsistec** [comment]
You open to pr's on https://github.com/AnthonyNahas/ionic-auth-firebaseui for Ionic v4, not sure based on ur last response? I dont have much time but I really like the work you have been releasing

**Comment by AnthonyNahas** [comment]
v4

for v2-3 we cann create a separated branch...

I am facing the issue of linking the ionic module with my 3rd party library...

I will appreciate really the help of the community...

**Comment by yetanotherspinner** [comment]
Hi Anthony, what is the current status of ionic support? I was able to use your library (with minor modifications) in ionic capacitor environment (to the extent I am interested in :-)) so I am curious to know when the "official" support will come... Thank you in advance.

**Comment by AnthonyNahas** [comment]
I am aiming to make this live in 2020 <3

**Comment by magoarcano** [comment]
+1 for this functionality!

**Comment by jackie-d** [comment]
Actually is there any way to open the social provider in a modal inside the app?

Or is the current mechanism working on a ionic app with some tweak?

**Comment by jackie-d** [comment]
Hi, just got in depth, and found that the most reason that cause incompatibility with Ionic projects is the impossibility to rely on the social logins via related providers as they got called by the 

`signInWithPopup` method instead of the mobile supported `signInWithRedirect` method.

See [auth-process service](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/2e5072c3ee55fe91f978ae353a37904e323dad92/projects/ngx-auth-firebaseui/src/lib/services/auth-process.service.ts#L106)

[Related discussion specifically for Ionic](https://forum.ionicframework.com/t/firebase-firebase-auth-signinwithpopup/91476/23)

It would not be so difficult to change the method signature from 

`public async signInWith(provider: AuthProvider, credentials?: ICredentials) {`

to 

`public async signInWith(provider: AuthProvider, credentials?: ICredentials, withRedirect?: boolean) {`

and bind an additional parameter to `ngx-auth-firebaseui-providers` component like `withRedirect` .

I don't find any other big limitation to use this inside a ionic/cordova project, beside the additional styling needed as it's not using default components, but for me that's a basilar optimization, not a limitation.

Would you be open to consider a PR for that and to enable the use of this library on mobile too?

Jackie

**Comment by mbaljeetsingh** [comment]
Hi 

Is the **Ionic 4/5** support in the works? I'm currently developing a app using Ionic. I guess I can use the current **Angular Material** supported library inside the Ionic project. But it'll be useful if the components have the **look and feel** similar to Ionic. 

So, Looking forward.
Thanks

**Comment by vbourdeix** [comment]
@jackie-d I was about to submit a pull request for that but apparently, there is already one here #581

**Comment by mcroker** [comment]
@AnthonyNahas I needed support for Ionic/Cordova for my own project, so have given the port a crack...

What I intended to be a quick port become a somewhat larger refactoring, partially because I had in mind that the ionic and Capacitor dependant features would be separately packaged (such that a material UI could be implemented alongside). And I also had to meet the requirements of my app.  I also wanted to ensure that the auth-pages could be lazily loaded, so they sit in a separate module from core.

The end result is I have:
- **core**: -Provides auth-process service (which build on the base from this package) plus the avatar component (potentially needed on every page)
- **UI abstraction (/ionic)**: which wraps alerts, toasts etc. (such that I can use the ionic native implementations, but it would be possible to implement for material too)
**- Firebase provider abstraction (/capacitor)**: which allows a facade for the relevant Capacitor plugins to be injected and used instead of angularFire when running on a native device (currently unsupported by angular/fire or firebase sdk).
**- Auth-pages module**: Which can be lazily loaded to the '/auth' route.

If nothing-else, I would imagine this would inform a ionic/capacitor implementation, and may very well be the seed of it.  Anyhoo enough pre-amble, the (currently very poorly documented) repo is here.

https://github.com/mcroker/ngx-firebase
